title: "QT量化交易"
github:
  repository_url: "/devlog/"
theme: jekyll-theme-modernist
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
baseurl: "/devlog"
collections:
  - reports